version: '3.1'

services:
  db:
    image: postgres:13.5
    privileged: true
    restart: always
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django123456
      POSTGRES_DB: todoproject

  backend:
    build: ./todoproject
    privileged: true
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: 'todoproject.settings'
    command: bash -c "
        python manage.py migrate &&
        python manage.py make_su &&
        python manage.py make_users &&
        gunicorn todoproject.wsgi -b 0.0.0.0:8080
      "
  
  nginx:
    build: ./nginx
    privileged: true
    ports:
      - 8000:80
    depends_on:
      - backend
  
  frontend:
    build: ./frontend
    privileged: true
    ports:
      - 80:80
    depends_on:
      - backend
   

