# Generated by Django 2.2.10 on 2021-12-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='git_link',
            field=models.URLField(blank=True),
        ),
    ]
